[graph]
all-features = true
exclude-dev = true

[bans]
multiple-versions = "allow"

# Not exhaustive, just whitelist the current dependency tree
[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "CC0-1.0",
  "GPL-3.0-only",
  "MIT",
  "MIT-0",
  "Unicode-3.0",
  "Zlib",
]

