#!/usr/bin/env sh
# SPDX-FileCopyrightText: © 2021 Caleb Maclennan <caleb@alerque.com>
# SPDX-License-Identifier: GPL-3.0-only

set -e

: "${ALPINETAG:=3.19.1}"

REVISION=$(git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g')

RUNTIME_DEPS='git'

: "${DOCKER_BUILDKIT:=1}"
export DOCKER_BUILDKIT

docker build \
	--build-arg ALPINETAG="$ALPINETAG" \
	--build-arg REVISION="$REVISION" \
	--build-arg VERSION="${1:-$REVISION}" \
	--build-arg RUNTIME_DEPS="$RUNTIME_DEPS" \
	--tag $DOCKER_REPO:$DOCKER_TAG \
	./
